#undef RF_CHANNEL
#define RF_CHANNEL      21

//#undef RPL_CONF_DIO_REDUNDANCY
//#define RPL_CONF_DIO_REDUNDANCY 5

//#undef RPL_CONF_DIO_INTERVAL_MIN 
//#define RPL_CONF_DIO_INTERVAL_MIN 30

//#undef RPL_CONF_DIO_INTERVAL_DOUBLINGS
//#define RPL_CONF_DIO_INTERVAL_DOUBLINGS 5

